# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        args: [ --fix ]
        language: python
        types_or: [python, pyi, jupyter]
        minimum_pre_commit_version: '4.0.1'
      - id: ruff-format
        description: "Run 'ruff format' for extremely fast Python formatting"
        language: python
        types_or: [python, pyi, jupyter]
        minimum_pre_commit_version: '4.0.1'

  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.11.2
      hooks:
        - id: mypy
          description: "Run 'mypy' for Python linting"
          language: python
          minimum_pre_commit_version: '4.0.1'

  # - repo: local
  #   hooks:
  #     - id: pytest-check
  #       name: pytest-check
  #       entry: poetry run pytest
  #       language: system
  #       pass_filenames: false
  #       always_run: true
