FROM python:3.11-slim

WORKDIR /migration

COPY . /migration

RUN apt-get update && apt-get install -y \
    curl \
    gcc \
    liblapack-dev \
    libblas-dev \
    libsuitesparse-dev \
    wget \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && curl -sSL https://install.python-poetry.org | python3 -

RUN export CPPFLAGS="-I/usr/include/suitesparse" \
    && poetry config virtualenvs.in-project true \
    && poetry install --no-interaction --no-ansi
